/* AUTOGENERATED FILE — credentials loaded from .env.local (see .env.example) */

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID as string;
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string;